### ISSUE TITLE
Can not work?

### ISSUE THREAD

**Issue by DustinChen1986** [bosborne/BioPythonUtils#2]
It seems do not work not.
I think the problem is that I install the biopython 1.69.

**Comment by bosborne** [comment]
What is the error message? Do "View" -> "Show Console".

**Comment by bosborne** [comment]
Any comment on this? BioPython is already in the package, so that can't be the problem. Otherwise I will close this.

**Comment by DustinChen1986** [comment]
Don't worry about this. Maybe the problem is my code, and I have use the latest version with everything is OK. Thank you for your attention.
